name: vieocore
description: A Decentralized Distributed Blockchain Application Server
version: 1.0.0
environment:
  sdk: ^3.0.1

dependencies:
  crypto: ^3.0.3
  web_socket_channel: ^2.4.0
  pointycastle: ^3.7.3
  alfred: ^1.1.1

dev_dependencies:
  test: ^1.16.0

flutter:
  # Replace with your specific Flutter version
  sdk: ^3.7.6

# Add any additional configuration or metadata here
